PAGE_RULES = [
    {
        "type": "roof_plan",
        "importance": "essential",
        "title_words": ["roof plan", "roof layout"],
        "support_words": ["roof", "parapet", "skylight", "plant", "north"],
    },
    {
        "type": "site_plan",
        "importance": "supporting",
        "title_words": ["site plan", "locality plan", "location plan"],
        "support_words": ["north", "boundary", "street", "site"],
    },
    {
        "type": "elevation",
        "importance": "supporting",
        "title_words": ["elevation", "shopfront elevation", "front elevation", "side elevation"],
        "support_words": ["glazing", "door", "window", "awning", "facade"],
    },
    {
        "type": "section",
        "importance": "supporting",
        "title_words": ["section", "building section", "ceiling section"],
        "support_words": ["ceiling", "roof", "slab", "floor level", "bulkhead"],
    },
    {
        "type": "reflected_ceiling_plan",
        "importance": "essential",
        "title_words": ["reflected ceiling plan", "rcp", "ceiling plan"],
        "support_words": [
            "air condition register",
            "supply slot diffuser",
            "diffuser",
            "grille",
            "ceiling height",
            "access panel",
            "sprinkler",
        ],
    },
    {
        "type": "floor_plan",
        "importance": "essential",
        "title_words": [
            "general arrangement plan",
            "dimension plan",
            "floor plan",
            "floor finish plan",
            "shop floor plan",
            "layout plan",
            "loose furniture plan",
            "main level construction annotation plan",
        ],
        "support_words": [
            "lease line",
            "room",
            "area",
            "office",
            "service counter",
            "dimensions",
        ],
    },
    {
        "type": "existing_hvac_or_services_plan",
        "importance": "useful",
        "title_words": [
            "mechanical services plan",
            "mechanical main level floor plan",
            "mechanical main garage floor plan",
            "mechanical ductwork main garage floor plan",
            "base building mechanical services",
            "existing services",
            "existing mechanical",
            "air conditioning plan",
            "ventilation plan",
            "ductwork plan",
            "pipework plan",
        ],
        "support_words": [
            "ductwork",
            "pipework",
            "ventilation",
            "fan coil",
            "fcu",
            "vav",
            "supply air",
            "return air",
            "outside air",
            "exhaust air",
        ],
    },
]

REFERENCE_RULES = [
    {
        "type": "hvac_or_rcp_legend",
        "importance": "reference",
        "packet_role": "symbol_key_context",
        "title_words": [
            "mechanical legend",
            "mechanical abbreviations",
            "mechanical notes",
            "mechanical symbols",
            "mechanical key",
            "hvac legend",
            "hvac symbols",
            "air conditioning legend",
            "air conditioning symbols",
            "ductwork legend",
            "diffuser schedule",
            "grille schedule",
            "register schedule",
            "rcp legend",
            "reflected ceiling plan legend",
            "ceiling services legend",
            "ceiling finish legend",
        ],
        "support_words": [
            "air condition register",
            "supply slot diffuser",
            "diffuser",
            "grille",
            "ductwork",
            "supply air",
            "return air",
            "outside air",
            "exhaust air",
            "fan coil",
            "fcu",
            "vav",
            "damper",
            "register",
            "access panel",
            "exhaust fan",
        ],
    },
    {
        "type": "equipment_or_fixture_schedule",
        "importance": "reference",
        "packet_role": "equipment_schedule_context",
        "title_words": [
            "equipment schedule",
            "kitchen equipment",
            "fixture schedule",
            "diffuser schedule",
            "grille schedule",
            "register schedule",
        ],
        "support_words": ["heat", "exhaust", "fridge", "dishwasher", "cooking", "hood", "diffuser", "grille"],
    },
    {
        "type": "bca_or_ventilation_notes",
        "importance": "reference",
        "packet_role": "code_or_ventilation_note_context",
        "title_words": ["ventilation notes", "mechanical ventilation", "as1668"],
        "support_words": ["mechanical ventilation", "ductwork", "air handling", "as4254", "as1668"],
    },
]

KNOWN_TITLES = [
    "Reflected Ceiling Plan",
    "General Arrangement Plan",
    "Shop Floor Plan",
    "Layout Plan",
    "Main Level Construction Annotation Plan",
    "Mechanical Services Plan",
    "Base Building Mechanical Services Plan",
    "Mechanical Main Level Floor Plan",
    "Mechanical Ductwork Main Garage Floor Plan",
    "Mechanical Main Level Demolition Floor Plan",
    "Plumbing Main Level Floor Plan",
    "Electrical Power Main Level Floor Plan",
    "Electrical Lighting Main Level Floor Plan",
    "Electrical Demolition Main Level Floor Plan",
    "Air Conditioning Plan",
    "Ventilation Plan",
    "Ductwork Plan",
    "Pipework Plan",
    "Ceiling Detail",
    "Bulkhead Detail",
]

IGNORE_TITLE_WORDS = [
    "cover page",
    "drawing list",
    "general conditions",
    "electrical abbreviations",
    "electrical symbols",
    "lighting symbols",
    "fire alarm legend",
    "electrical general notes",
    "electrical lighting notes",
    "electrical power notes",
    "electrical technology notes",
    "electrical demolition notes",
    "lighting switch and sensor tags",
    "lighting fixture tags",
    "lighting calculations",
    "luminaire schedule",
    "structural engineering",
    "structural drawings",
]

DISCARD_RULES = [
    {
        "type": "cover_or_drawing_list",
        "words": ["cover page", "drawing list", "proposed project at"],
    },
    {
        "type": "document_repository_cover",
        "words": [
            "repository citation",
            "special collections and archives",
            "accepted for inclusion",
            "part of the environmental design commons",
            "brought to you by oasis",
        ],
    },
    {
        "type": "electrical_or_fire",
        "words": [
            "electrical abbreviations",
            "electrical symbols",
            "lighting symbols",
            "fire alarm legend",
            "electrical general notes",
            "electrical lighting notes",
            "electrical power notes",
            "electrical technology notes",
            "electrical demolition notes",
            "lighting switch and sensor tags",
            "lighting fixture tags",
            "lighting calculations",
            "luminaire schedule",
        ],
    },
    {
        "type": "structural",
        "words": ["structural engineering", "structural drawings"],
    },
    {
        "type": "architectural_detail_noise",
        "words": [
            "blowup detail",
            "bulkhead detail",
            "cabinet detail",
            "ceiling section",
            "door schedule",
            "schedule of doors",
            "door battens",
            "3d images perspective",
            "site photo reference",
            "signage detail",
            "signage",
        ],
    },
    {
        "type": "lighting_or_energy_report",
        "words": [
            "non-residential lighting calculator",
            "satisfies part j7d3",
            "lighting system power",
            "lighting-ncc",
        ],
    },
]

TOP_VIEW_WORDS = [
    "reflected ceiling plan",
    "rcp",
    "ceiling plan",
    "floor plan",
    "dimension plan",
    "floor finish plan",
    "general arrangement plan",
    "layout plan",
    "loose furniture plan",
    "mechanical services plan",
    "air conditioning plan",
    "ventilation plan",
    "ductwork plan",
    "pipework plan",
]

NON_HVAC_DISCIPLINES = ["electrical", "plumbing", "fire alarm", "structural"]

CEILING_CONSTRAINT_WORDS = [
    "access panel",
    "sprinkler",
    "smoke detector",
    "light fixture",
    "lighting",
    "ceiling grid",
    "ceiling height",
    "ceiling line",
    "bulkhead",
    "existing ceiling",
    "duct penetration",
]

HVAC_WORDS = [
    "air condition register",
    "supply slot diffuser",
    "diffuser",
    "grille",
    "ductwork",
    "pipework",
    "ventilation",
    "fan coil",
    "fcu",
    "vav",
    "supply air",
    "return air",
    "outside air",
    "exhaust air",
    "air flow",
]
